AWSTemplateFormatVersion: '2010-09-09'
Description: Layer 2 - Security Groups

Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      VpcId: !ImportValue MiniProj-VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SQL from WebApp
      VpcId: !ImportValue MiniProj-VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref WebSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref WebSecurityGroup

Outputs:
  WebSGId:
    Value: !Ref WebSecurityGroup
    Export: {Name: MiniProj-WebSGId}
  DBSGId:
    Value: !Ref DBSecurityGroup
    Export: {Name: MiniProj-DBSGId}